# https://help.github.com/en/actions
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
# https://github.com/actions

# https://github.com/micro-os-plus/diag-trace-xpack/actions/workflows/ci.yml
name: CI on Push

on:
  push:
    paths-ignore:
      - '.vscode/**'
      - 'LICENSE'
      - '**.md'
      - '.clang-format'
      - '.gitignore'
      - '.npmignore'
      - '.github/workflows/test-all.yml'
      - 'tests-xpack/scripts/**'
    # This should disable running the workflow on tags, according to the
    # on.<push|pull_request>.<branches|tags> GitHub Actions docs.
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
    branches:
      - '*'

jobs:
  ci-test:
    name: 'CI googletest tests'

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18]
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
        os: [ubuntu-22.04, macos-12, windows-2022]
        xpm-version: ['0.16.2']

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 3

    - name: Setup Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Show environment
      run: |
        uname -a
        node --version
        npm --version
        env

    - name: Install xpm@${{ matrix.xpm-version }} on Unix
      if: runner.os != 'Windows'
      run: sudo npm install -g xpm@${{ matrix.xpm-version }}

    - name: Install xpm@${{ matrix.xpm-version }} on Windows
      if: runner.os == 'Windows'
      run: npm install -g xpm@${{ matrix.xpm-version }}

    - name: Satisfy project dependencies
      run: xpm install

    - name: Run test-native-cmake-gcc11
      run: |
        xpm install --config native-cmake-gcc11-debug
        xpm install --config native-cmake-gcc11-release
        xpm run test-native-cmake-gcc11

    - name: Run test-native-cmake-clang12
      run: |
        xpm install --config native-cmake-clang12-debug
        xpm install --config native-cmake-clang12-release
        xpm run test-native-cmake-clang12

    - name: Run test-native-meson-gcc11
      run: |
        xpm install --config native-meson-gcc11-debug
        xpm install --config native-meson-gcc11-release
        xpm run test-native-meson-gcc11

    - name: Run test-qemu-mps2-an386-cmake
      run: |
        xpm install --config qemu-mps2-an386-cmake-debug
        xpm install --config qemu-mps2-an386-cmake-release
        xpm run test-qemu-mps2-an386-cmake

    - name: Run test-qemu-mps2-an386-meson
      run: |
        xpm install --config qemu-mps2-an386-meson-debug
        xpm install --config qemu-mps2-an386-meson-release
        xpm run test-qemu-mps2-an386-meson
